spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa.hibernate.ddl-auto: update
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
server.port: 8084

